defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "PATH_TO_DATA"
  dataset_name: "cylinder-flow" 
  ntrain : 
  ntest : 
  sub_from : 1
  sub_tr : 1 #0.015625
  sub_te : 1 #0.015625
  seed: 123
  same_grid: True
  seq_inter_len : 30 
  seq_extra_len : 0

optim:
  batch_size: 128
  batch_size_val: 
  lr : 1e-3
  gamma_step : 0.9
  lr_code : 0.01
  weight_decay: 0
  epochs : 5000
  min_noise: 1e-3
  threshold: 1.0

wandb:
  entity: "spatiotemp-isir"
  project: aroma
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : True #False
  checkpoint_path:  
  
model:
  hidden_size: 128 #192,#1152,
  depth: 4 #4
  num_heads: 4 #6
  mlp_ratio: 4.0 #4.0
  class_dropout_prob: 0.1