defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "/data/wangt/mp_pde"
  dataset_name: "mp-pde-burgers" 
  ntrain : 
  ntest : 
  sub_from : 1
  sub_tr : 2 #0.015625
  sub_te : 2 #0.015625
  seed: 123
  same_grid: True
  seq_inter_len : 50 # we change this
  seq_extra_len : 0 # we change this

optim:
  batch_size: 1024
  batch_size_val: 
  lr_inr : 1e-3
  gamma_step : 0.9
  lr_code : 0.01
  weight_decay_code: 1e-3
  epochs : 1000
  weight_decay: 0.01


wandb:
  entity: "spatiotemp-isir"
  project: aroma
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : False #False
  checkpoint_path : 

inr:
  hidden_dim: 128 
  dim: 128
  depth_inr: 3 #2
  num_self_attentions: 2
  num_latents: 32 #16
  latent_dim: 8 #8
  latent_heads: 4
  latent_dim_head: 32 #64
  cross_heads: 4
  cross_dim_head: 32 #64
  kl_weight: 0 #1e-4 # autoencoder
  frequencies: [3, 4, 5]
  num_freq: 12
  dropout_sequence: 0.1
  mlp_feature_dim: 16
  bottleneck_index: 0
  encode_geo: False 
  max_pos_encoding_freq: 4
  sample_posterior: True # autoencoder