defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

data:
  dir: "PATH_TO_DATA"
  dataset_name: "navier-stokes-1e-5" 
  ntrain : 
  ntest : 
  sub_from : 1
  sub_tr : 1 
  sub_te : 1
  seed: 123
  same_grid: True
  seq_inter_len : 20 
  seq_extra_len : 0

optim:
  batch_size: 10 
  batch_size_val: 
  lr_inr : 1e-3
  gamma_step : 0.9
  lr_code : 0.01
  weight_decay: 0
  epochs : 2000

wandb:
  entity: "spatiotemp-isir"
  project: aroma
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : False #False
  checkpoint_path : 

inr:
  hidden_dim: 256 
  dim: 256
  depth_inr: 3 #2
  encode_geo: False 
  bottleneck_index: 0
  num_self_attentions: 2
  num_latents: 256 #16
  latent_dim: 16 #8
  mlp_feature_dim: 16
  latent_heads: 4
  latent_dim_head: 32 #64
  cross_heads: 4
  cross_dim_head: 32 #64
  sample_posterior: True # autoencoder
  kl_weight: 1e-5
  dropout_sequence: 0.10
  frequencies: [3, 4, 5]
  max_pos_encoding_freq: 4
  num_freq: 12
